version: '3.7'
services:
  postgres_db:
    container_name: 'dev-postgres'
    image: 'postgres:13'
    ports:
      - '5432:5432'
    volumes:
      - './pgdata:/var/lib/postgresql/data/'
    environment:
      - POSTGRES_PASSWORD=asdqwe1234
